# Generated by Django 3.1.7 on 2021-06-20 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user_id',
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(blank=True, db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='AVATAR', max_length=32, null=True, upload_to='avatar'),
        ),
    ]
